//
// AUTOGENERATED SOURCE - DO NOT EDIT
//

#include "types/CDeviceDESD.hpp"
#include "types/CDeviceSST.hpp"
#include "types/CDeviceDRER.hpp"
#include "types/CDeviceLOAD.hpp"

namespace freedm {
namespace broker {
namespace device {

/// Registers the physical devices known to this file with the device factory
void RegisterPhysicalDevices();

}
}
}