// THIS FILE IS AUTOGENERATED

#include <string>

#ifndef CTIMINGS_HPP
#define CTIMINGS_HPP

namespace freedm {
namespace broker {

class CTimings
{
public:
$parameter_block
    static void SetTimings(const std::string timingsFile);
};


}
}

#endif
